
when:
  - event: push
    branch: main

steps:
  - name: build-and-push:
    image: woodpeckerci/plugin-docker
    settings:
      dockerfile: ./mammamia/Dockerfile
      context: ./mammamia
      repo: registry.oci.w3studio.it/mammamia
      tags: latest
      registry: registry.oci.w3studio.it
      username: from_secret:REGISTRY_USER
      password: from_secret:REGISTRY_PASS

