when:
  - event: push
    branch: main
steps:

  
  update-stack:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker service update --force --image registry.oci.w3studio.it/streamv:latest --with-registry-auth stremio_streamv
