
when:
  - event: push
    branch: main

steps:
  - name: build
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t registry.oci.w3studio.it/mammamia:latest ./mammamia
      - docker build -t registry.oci.w3studio.it/mfp:latest ./mfp

  - name: push
    image: docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - OCI_REGISTRY_USER
      - OCI_REGISTRY_PASS
    commands:
      - echo "$REGISTRY_PASS" | docker login -u "$OCI_REGISTRY_USER" --password-stdin registry.oci.w3studio.it
      - docker push registry.oci.w3studio.it/mammamia:latest
      - docker push registry.oci.w3studio.it/mfp:latest
