when:
  - event: push
    branch: main
steps:
  build-webstreamr:
    image: woodpeckerci/plugin-docker-buildx:6.0.1
    settings:
      context: "https://github.com/webstreamr/webstreamr.git#main"
      dockerfile: Dockerfile
      repo: registry.oci.w3studio.it/webstreamr
      tags: latest, ${CI_COMMIT_SHA}
      push: true
      registry: registry.oci.w3studio.it
      username:
        from_secret: OCI_REGISTRY_USER
      password:
        from_secret: OCI_REGISTRY_PASSWORD
  

      
      

