
when:
  - event: push
    branch: main

steps:
  build-mammamia:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: ./mammamia/Dockerfile
      context: ./mammamia
      repo: registry.oci.w3studio.it/mammamia
      tags: latest
      registry: registry.oci.w3studio.it
      username: from_secret:OCI_REGISTRY_USER
      password: from_secret:OCI_REGISTRY_PASSWORD

  build-mfp:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: ./mfp/Dockerfile
      context: ./mfp
      repo: registry.oci.w3studio.it/mfp
      tags: latest
      registry: registry.oci.w3studio.it
      username: from_secret:OCI_REGISTRY_USER
      password: from_secret:OCI_REGISTRY_PASSWORD

