when:
  - event: push
    branch: main
steps:

  build-streamv:
    image: woodpeckerci/plugin-docker-buildx:6.0.1
    settings:
      dockerfile: ./streamv/Dockerfile
      context: ./streamv
      repo: registry.oci.w3studio.it/streamv
      tags: latest, ${CI_COMMIT_SHA}
      push: true
      registry: registry.oci.w3studio.it
      username:
        from_secret: OCI_REGISTRY_USER
      password:
        from_secret: OCI_REGISTRY_PASSWORD
  
  update-stack:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker service update --image registry.oci.w3studio.it/streamv:${CI_COMMIT_SHA}  --with-registry-auth stremio_streamv
