version: '3.8'

services:
  mediaflow_proxy:
    build: ./media_proxy
    container_name: mediaflow_proxy
    environment:
      - API_PASSWORD=your_mfp_password
      - 'TRANSPORT_ROUTES={"all://*.ichigotv.net": {"verify_ssl": false}, "all://ichigotv.net": {"verify_ssl": false}}'

  mammamia:
    build: ./mammamia
    container_name: mammamia
    environment:
      - TMDB_KEY=set_your_tmdbkey
      - 'PROXY=["the proxy"]'
      - 'FORWARDPROXY=the forward proxy/'
    
networks:
  default:
    external: true
    name: ix-nginx-proxy-manager_default
