version: '3.8'

services:
  mediaflow_proxy:
    build: ./media_proxy
    container_name: mediaflow_proxy
  mammamia:
    build: ./mammamia
    container_name: mammamia
    
networks:
  default:
    external: true
    name: ix-nginx-proxy-manager_default
