version: '3.8'

services:
  mediaflow_proxy:
    build: ./media_proxy
    container_name: mediaflow_proxy
    environment:
      - API_PASSWORD=${API_PASSWORD}
      - 'TRANSPORT_ROUTES={"all://*.ichigotv.net": {"verify_ssl": false}, "all://ichigotv.net": {"verify_ssl": false}}'

  mammamia:
    build: ./mammamia
    container_name: mammamia
    environment:
      - TMDB_KEY=${TMDB_KEY}
      - PROXY=${PROXY}
      - FORWARDPROXY=${FORWARDPROXY}
    
networks:
  default:
    external: true
    name: ix-nginx-proxy-manager_default
