version: '3.8'

services:
  mediaflow_proxy:
    image: registry.oci.w3studio.it/media_flow_proxy:latest
    environment:
      - API_PASSWORD=${API_PASSWORD}
      - 'TRANSPORT_ROUTES={"all://*.ichigotv.net": {"verify_ssl": false}, "all://ichigotv.net": {"verify_ssl": false}}'
      - FORWARDED_ALLOW_IPS=${FORWARDED_ALLOW_IPS}
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.media_proxy.rule=Host(`mfp.oci.w3studio.it`)"
        - "traefik.http.routers.media_proxy.entrypoints=websecure"
        - "traefik.http.routers.media_proxy.tls.certresolver=ovh"
        - "traefik.http.services.media_proxy.loadbalancer.server.port=8888"
    networks:
      - traefik-net
  mammamia:
    image: registry.oci.w3studio.it/mammamia:latest
    environment:
      - TMDB_KEY=${TMDB_KEY}
      - PROXY=${PROXY}
      - FORWARDPROXY=${FORWARDPROXY}
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mammamia.rule=Host(`mammamia.oci.w3studio.it`)"
        - "traefik.http.routers.mammamia.entrypoints=websecure"
        - "traefik.http.routers.mammamia.tls.certresolver=ovh"
        - "traefik.http.services.mammamia.loadbalancer.server.port=8080"
    networks:
      - traefik-net
  streamv:
    image: registry.oci.w3studio.it/streamv:latest
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
      - MFP_URL=${MFP_URL}
      - MFP_PSW=${MFP_PSW}
      - BOTHLINK=${BOTHLINK}
      - ANIMEUNITY_ENABLED=${ANIMEUNITY_ENABLED}
      - ANIMESATURN_ENABLED=${ANIMESATURN_ENABLED}
    command: pnpm start
    networks:
      - traefik-net
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.streamv.rule=Host(`streamv.oci.w3studio.it`)"
        - "traefik.http.routers.streamv.entrypoints=websecure"
        - "traefik.http.routers.streamv.tls.certresolver=ovh"
        - "traefik.http.services.streamv.loadbalancer.server.port=7860"
  #webstreamr:
  #  image: registry.oci.w3studio.it/webstreamr:latest
  #  networks:
  #    - traefik-net
  #  deploy:
  #    replicas: 1
  #    labels:
  #      - "traefik.enable=true"
  #      - "traefik.http.routers.webstreamr.rule=Host(`webstreamr.oci.w3studio.it`)"
  #      - "traefik.http.routers.webstreamr.entrypoints=websecure"
  #      - "traefik.http.routers.webstreamr.tls.certresolver=ovh"
  #      - "traefik.http.services.webstreamr.loadbalancer.server.port=51546"
  


networks:
  traefik-net:
    external: true
